### ISSUE TITLE
Idea: label entry from file

### ISSUE THREAD

**Issue by rhalkyard** [fijam/gmdrec#13]
A nice enhancement to the `only_label` mode, would be to read labels from a file instead of generating them from a playlist. Just something really simple, plain text, each line corresponds to a track. This would be useful for labelling a disc that you don't have a matching playlist for, or for making custom labels.

**Comment by fijam** [comment]
I have been thinking about something like that. I'd like to keep the UI as simple as it is (and it's already becoming a bit cluttered). I initially thought about a small utility that would take a list of tracks and create a 'fake' playlist which can be then loaded in foobar and labelled as usual. I still need to give it some thought.

**Comment by cory5412** [comment]
Hi, I know this is an older thread but just wanted to add: "me too".

With the addition of: If it's possible, I would love to have the device place track marks as well, because some discs I make are from streaming services.

I don't know if there's a good format for data for this but my initial thought was to use a spreadsheet program to make tab-separated files with time in one column and the track name in another. (tab-separated just because I can see a scenario where I'd use a comma in a disc or song title.)

Thank you for your consideration on this!

**Comment by fijam** [comment]
Thanks for the feedback. I'll need to think about the best way to implement it (I'd like to avoid making the UI more complicated than it is if possible).

**Comment by fijam** [comment]
Ideally, I would like this functionality handled by foobar2000 as much as possible. For example, for Spotify you should be able to use https://lukasticky.gitlab.io/spotify-to-m3u/ to convert a Spotify playlist to m3u, open it in foobar2000 and use that to label a recorded disc. It should be also fairly easy to make a small utility that would convert a .csv file into a m3u in the same fashion (I'll look into that). 

This however assumes that the recorded disc is already divided into tracks.

**Comment by fijam** [comment]
The functionality is now explained in: https://github.com/fijam/gmdrec/wiki/Label-from-a-file and will be available in the 0.7.1 point release.

Unfortunately, the track marks must be already present on the MD since foobar2000 ignores track duration saved in EXTM3U format (`#EXTINF` tag)

**Comment by fijam** [comment]
Fixed in https://github.com/fijam/gmdrec/releases/tag/v0.7.1
